# Generated by Django 4.1.2 on 2023-02-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
