# Generated by Django 4.1.2 on 2022-12-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
